version: '3.7'

services:
  cabinet:
    container_name: library
    image: postgres:latest
    hostname: localhost
    ports:
      - 5435:5432
    env_file:
      - .env
    restart: unless-stopped
